path = r'D:\qoder\vertax\src\lib\publishers\supabase-adapter.ts'
with open(path, 'rb') as f:
    d = f.read()

old = (
    b"/**\r\n"
    b" * \xe4\xbb\x8e WebsiteConfig \xe5\x88\x9b\xe5\xbb\xba PublisherAdapter\r\n"
    b" */\r\n"
    b"export function createPublisherAdapter(config: {\r\n"
    b"  siteType: string;\r\n"
    b"  supabaseUrl: string | null;\r\n"
    b"  functionName: string | null;\r\n"
    b"  pushSecret: string | null;\r\n"
    b"}): PublisherAdapter {\r\n"
    b"  if (config.siteType !== \"supabase\") {\r\n"
    b"    throw new Error(`Unsupported site type: ${config.siteType}. Currently only 'supabase' is supported.`);\r\n"
    b"  }\r\n"
    b"\r\n"
    b"  if (!config.supabaseUrl || !config.functionName || !config.pushSecret) {\r\n"
    b"    throw new Error(\"Missing Supabase configuration: supabaseUrl, functionName, and pushSecret are required.\");\r\n"
    b"  }\r\n"
    b"\r\n"
    b"  return new SupabasePublisherAdapter({\r\n"
    b"    supabaseUrl: config.supabaseUrl,\r\n"
    b"    functionName: config.functionName,\r\n"
    b"    pushSecret: config.pushSecret,\r\n"
    b"  });\r\n"
    b"}\r\n"
)
new = (
    b"/**\r\n"
    b" * \xe5\xb7\xa5\xe5\x8e\x82\xe5\x87\xbd\xe6\x95\xb0\xef\xbc\x9a\xe6\xa0\xb9\xe6\x8d\xae siteType \xe5\x88\x9b\xe5\xbb\xba\xe5\xaf\xb9\xe5\xba\x94 PublisherAdapter\r\n"
    b" *\r\n"
    b" * siteType \xe8\xb7\xaf\xe7\x94\xb1\xef\xbc\x9a\r\n"
    b" *   supabase   \xe2\x86\x92 SupabasePublisherAdapter  (POST to Supabase Edge Function)\r\n"
    b" *   nextjs     \xe2\x86\x92 WebhookPublisherAdapter   (POST + HMAC-SHA256, \xe8\x87\xaa\xe7\xa0\x94 Next.js \xe7\xab\x99)\r\n"
    b" *   wordpress  \xe2\x86\x92 WordPressPublisherAdapter (WP REST API v2)\r\n"
    b" *   rest       \xe2\x86\x92 RestPublisherAdapter      (\xe9\x80\x9a\xe7\x94\xa8 Bearer token REST)\r\n"
    b" */\r\n"
    b"export function createPublisherAdapter(config: PublisherAdapterConfig): PublisherAdapter {\r\n"
    b"  switch (config.siteType) {\r\n"
    b"    case \"supabase\": {\r\n"
    b"      if (!config.supabaseUrl || !config.functionName || !config.pushSecret) {\r\n"
    b"        throw new Error(\"Supabase adapter requires: supabaseUrl, functionName, pushSecret\");\r\n"
    b"      }\r\n"
    b"      return new SupabasePublisherAdapter({\r\n"
    b"        supabaseUrl: config.supabaseUrl,\r\n"
    b"        functionName: config.functionName,\r\n"
    b"        pushSecret: config.pushSecret,\r\n"
    b"      });\r\n"
    b"    }\r\n"
    b"\r\n"
    b"    case \"nextjs\": {\r\n"
    b"      if (!config.webhookUrl || !config.pushSecret) {\r\n"
    b"        throw new Error(\"Next.js webhook adapter requires: webhookUrl, pushSecret\");\r\n"
    b"      }\r\n"
    b"      return new WebhookPublisherAdapter({\r\n"
    b"        webhookUrl: config.webhookUrl,\r\n"
    b"        pushSecret: config.pushSecret,\r\n"
    b"        customHeaders: config.customHeaders ?? undefined,\r\n"
    b"      });\r\n"
    b"    }\r\n"
    b"\r\n"
    b"    case \"wordpress\": {\r\n"
    b"      if (!config.wpUrl || !config.wpUsername || !config.wpPassword) {\r\n"
    b"        throw new Error(\"WordPress adapter requires: wpUrl, wpUsername, wpPassword\");\r\n"
    b"      }\r\n"
    b"      return new WordPressPublisherAdapter({\r\n"
    b"        siteUrl: config.wpUrl,\r\n"
    b"        username: config.wpUsername,\r\n"
    b"        password: config.wpPassword,\r\n"
    b"      });\r\n"
    b"    }\r\n"
    b"\r\n"
    b"    case \"rest\": {\r\n"
    b"      if (!config.webhookUrl) {\r\n"
    b"        throw new Error(\"REST adapter requires: webhookUrl\");\r\n"
    b"      }\r\n"
    b"      return new RestPublisherAdapter({\r\n"
    b"        endpointUrl: config.webhookUrl,\r\n"
    b"        pushSecret: config.pushSecret ?? undefined,\r\n"
    b"        customHeaders: config.customHeaders ?? undefined,\r\n"
    b"      });\r\n"
    b"    }\r\n"
    b"\r\n"
    b"    default:\r\n"
    b"      throw new Error(`Unsupported siteType: \"${config.siteType}\". Valid values: supabase | nextjs | wordpress | rest`);\r\n"
    b"  }\r\n"
    b"}\r\n"
)
assert old in d, 'factory pattern not found'
d = d.replace(old, new, 1)
with open(path, 'wb') as f:
    f.write(d)
print('OK')
